name: Deploy to Github Pages Branch
on:
  push:	
    branches:	
      - main

jobs:
  deploy:
    name: Deploy to Github Pages Branch
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@main
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo install dnd_wiki
      - run: dnd_wiki
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}